import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Navbar from "@/components/default/navbar";
import Footer from "@/components/default/footer";

import localFont from "next/font/local";
import { Roboto, Montserrat, Open_Sans } from "next/font/google";
import { ThemeProvider as NextThemesProvider } from "next-themes";

const geistMono = localFont({
  src: "../public/assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const openSans = Open_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${roboto.variable} ${montserrat.variable} ${openSans.variable} antialiased`}
      >
        <NextUIProvider>
          <NextThemesProvider attribute="class" defaultTheme="dark">
            <div className="w-full max-w-screen-2xl mx-auto">
              <Navbar />
              {children}
              <Footer />
            </div>
          </NextThemesProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
